import Head from "next/head";
import NavDrawer from "../../layout/NavDrawer";

const Companies = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Companies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

Companies.Layout = NavDrawer;

export default Companies;
