import Head from "next/head";
import NavDrawer from "../../layout/NavDrawer";

const Domains = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Domains</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

Domains.Layout = NavDrawer;

export default Domains;
