import Head from "next/head";
import NavDrawer from "../../layout/NavDrawer";

const FactoryDevices = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Factory Devices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

FactoryDevices.Layout = NavDrawer;

export default FactoryDevices;
