import Head from 'next/head'
import NavDrawer from '../../layout/NavDrawer';


const Passwords = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Passwords Settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

Passwords.Layout = NavDrawer;

export default Passwords;