import Head from "next/head";
import NavDrawer from "../../layout/NavDrawer";

const PurgedUser = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Purged User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

PurgedUser.Layout = NavDrawer;

export default PurgedUser;
