import Head from 'next/head'
import NavDrawer from '../../layout/NavDrawer';


const Refunds = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Refunds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

Refunds.Layout = NavDrawer;

export default Refunds;