import Head from 'next/head'
import NavDrawer from '../../layout/NavDrawer';
import { UserListResults } from "../../components/user/user-list-results";
import { UserListToolbar } from "../../components/user/user-list-toolbar";
import { users } from '../../__mocks__/users';
import { Box } from '@mui/material';

const UserList = () => (
  <Box
    maxWidth="xs"
    sx={{
      flexGrow: 1,
      py: 6,
    }}
  >
    <UserListToolbar />
    <Box sx={{ mt: 3 }}>
      <UserListResults users={users} />
    </Box>
  </Box>
)

const Users = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserList />
    </>
  )
}

Users.Layout = NavDrawer;

export default Users;