import Head from 'next/head'
import { styled } from '@mui/material/styles';
import { Box, Button, ButtonGroup, Card, CardActions, CardContent, CardHeader, IconButton, ListItemText, Menu, MenuItem } from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import MoreVertIcon from '@mui/icons-material/MoreVert';

import NavDrawer from '../../layout/NavDrawer';

import SplitButton from '../../components/SplitButton';
import ListResults from '../../components/list-results';

import { userListColumns } from "../../components/columns/user-list-columns";
import { users } from '../../__mocks__/users';

const ExpandMore = styled((props) => {
  const { expand, ...other } = props;
  return <IconButton {...other} />;
})(({ theme, expand }) => ({
  transform: !expand ? 'rotate(0deg)' : 'rotate(180deg)',
  marginLeft: 'auto',
  transition: theme.transitions.create('transform', {
    duration: theme.transitions.duration.shortest,
  }),
}));

const Users = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card
        sx={{
          m: 2,
          height: 1
        }}>
        <CardHeader
          component={Box}
          title="Users"
          // action={
          //   <Button
          //     variant="contained"
          //   >
          //     Add User
          //   </Button>
          // }
          sx={{
            color: 'primary.main',
            boxShadow: "0px 0px 1px grey"
          }}
        />
        <CardContent>
          <Box sx={{ mt: 3 }}>
            <ListResults rows={users} columns={userListColumns}/>
          </Box>
        </CardContent>
        <CardActions>
          <Button variant="contained">Add User</Button>
          <Button variant="contained">Activate</Button>
          <Button variant="contained">Deactivate</Button>
          <SplitButton />
          <Button variant="contained" >
            Deactivate
          </Button>
          <Menu>
            <MenuItem>
              <ListItemText >About</ListItemText>
            </MenuItem>
            <MenuItem>
              <ListItemText >About</ListItemText>
            </MenuItem>
          </Menu>
        </CardActions>
      </Card>
    </>
  )
}

Users.Layout = NavDrawer;

export default Users;