import { v4 as uuid } from 'uuid';

export const users =
[
	{
		"id" : 1,
		"username" : "12",
		"firstname" : "MD",
		"lastname" : "Admin",
		"email" : "test.t@gmail.com",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "Street",
		"profile" : "",
		"country" : "IT",
		"city" : "Altino"
	},
	{
		"id" : 2,
		"username" : "12",
		"firstname" : "Factory ",
		"lastname" : "Workstation",
		"email" : "tt@md-softwaredesign.de",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "Test street 123",
		"profile" : "",
		"country" : "IT",
		"city" : "Fontanelle"
	},
	{
		"id" : 4,
		"username" : "asd",
		"firstname" : "Alex",
		"lastname" : "Mitra",
		"email" : "tt2@md-softwaredesign.de",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "Test street 123",
		"profile" : "",
		"country" : "IT",
		"city" : "Fontanelle"
	},
	{
		"id" : 7,
		"username" : "asd",
		"firstname" : "Michael",
		"lastname" : "Dudenko",
		"email" : "tt3@md-softwaredesign.de",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "StreetNumber",
		"profile" : "2193f21ecf1d6cf0590b853a086bc439.png",
		"country" : "BE",
		"city" : "Alfter"
	},
	{
		"id" : 8,
		"username" : "asd",
		"firstname" : "Manish",
		"lastname" : "Vagh",
		"email" : "tt4@gmail.com",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "Bergmannstraße, 10961 Berlin, Germany",
		"profile" : "b81793a937afbca349f5c0a11eb9314a.png",
		"country" : "BE",
		"city" : "Berlin"
	},
	{
		"id" : 10,
		"username" : "asd",
		"firstname" : "Vladimir",
		"lastname" : "Dujin",
		"email" : "tt5@md-softwaredesign.de",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "Hauptstrase 75a",
		"phone" : "+388 22 00 22",
		"mobile" : "+388 99 99 11",
		"profile" : "f78b3ba4d6c1b7264325035861a00625.png",
		"country" : "BE",
		"city" : "Uebigau"
	},
	{
		"id" : 12,
		"username" : "asd",
		"firstname" : "Marijana",
		"lastname" : "Admin",
		"email" : "tt7@md-softwaredesign.de",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "Street",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : "c7e89bd54bced66642e84520cda27a0c.png",
		"country" : "BE",
		"city" : "Aachen"
	},
	{
		"id" : 14,
		"username" : "12",
		"firstname" : "Hans",
		"lastname" : "Weber",
		"email" : "test01@md-softwaredesign.de",
		"userRole" : "MD admin",
		"active" : 1,
		"company" : "eWheel",
		"active" : 1,
		"street" : "Lange Weg 44",
		"phone" : "+388 99 99 55 22 11",
		"fax" : null,
		"mobile" : null,
		"profile" : "",
		"country" : "DE",
		"city" : "Ahlden"
	},
	{
		"id" : 22,
		"username" : "asd",
		"firstname" : "test",
		"lastname" : "test",
		"email" : "test.02@md-softwaredesign.de",
		"userRole" : "MD admin",
		"active" : 1,
		"company" : "eWheel",
		"active" : 1,
		"street" : "stre",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : null,
		"country" : "DE",
		"city" : "Aach"
	},
	{
		"id" : 26,
		"username" : "asd",
		"firstname" : "Hardik",
		"lastname" : "Sorathiya",
		"email" : "tt7@gmail.com",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "test",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : "4ea42b543887594c15f6d5baffb1a5fa.png",
		"country" : "BE",
		"city" : "Aach"
	},
	{
		"id" : 34,
		"username" : "asd",
		"firstname" : "Svetozar",
		"lastname" : "Stojsin",
		"email" : "test4@md-softwaredesign.de",
		"userRole" : "MD admin",
		"active" : 1,
		"company" : "eWheel",
		"active" : 1,
		"street" : "Henri-Spaak-Straße 176",
		"phone" : "01 123456",
		"fax" : null,
		"mobile" : "02 123456",
		"profile" : "33465f4df2c45d177720714f06611dc1.png",
		"country" : "BE",
		"city" : "Alfter"
	},
	{
		"id" : 36,
		"username" : "12",
		"firstname" : "Svetozar",
		"lastname" : "Stojsin",
		"email" : "36.stojsin@md-softwaredesign.de",
		"userRole" : "MD admin",
		"active" : 1,
		"company" : "eWheel",
		"active" : 1,
		"street" : "Streeet 1234",
		"phone" : "01 123456",
		"fax" : null,
		"mobile" : "02 123456",
		"profile" : null,
		"country" : "BE",
		"city" : "Alfter"
	},
	{
		"id" : 44,
		"username" : "35",
		"firstname" : "André",
		"lastname" : "Gebauer",
		"email" : "test@testirs-group.com",
		"userRole" : "Client - Admin",
		"active" : 1,
		"company" : "eWheel",
		"active" : 1,
		"street" : "StreetNumber",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : "7f253e479708f6ab2f39eed31dd08917.png",
		"country" : "BE",
		"city" : "Kaltenkirchen"
	},
	{
		"id" : 125,
		"username" : "asd",
		"firstname" : "Norbert",
		"lastname" : "Reichmann",
		"email" : "tt@testirs-group.com",
		"userRole" : "Client - Admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "Strasse",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : "",
		"country" : "BE",
		"city" : "Rellingen"
	},
	{
		"id" : 141,
		"username" : "asd",
		"firstname" : "Ivana",
		"lastname" : "Zima",
		"email" : "test02@md-softwaredesign.de",
		"userRole" : "MD admin",
		"company" : "eWheel",
		"active" : 1,
		"street" : "Street",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : "",
		"country" : "BE",
		"city" : "Alfter"
	},
	{
		"id" : 207,
		"username" : "asd",
		"firstname" : "Eyan",
		"lastname" : "Decad",
		"email" : "tiger.cis+098@gmail.com",
		"userRole" : "MD admin",
		"active" : 1,
		"company" : "eWheel",
		"active" : 1,
		"street" : "Test",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : "",
		"country" : "BE",
		"city" : "Aachen"
	},
	{
		"id" : 265,
		"username" : "asd",
		"firstname" : "Ivana",
		"lastname" : "Zima",
		"email" : "test@md-softwaredesign.de",
		"userRole" : "MD admin",
		"active" : 1,
		"company" : "IZ company",
		"active" : 1,
		"street" : "Hauptstr. 12",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : "",
		"country" : "BE",
		"city" : "Aach"
	},
	{
		"id" : 269,
		"username" : "22",
		"firstname" : "Katinka",
		"lastname" : "Möhrle",
		"email" : "test@wheelwizard.de",
		"userRole" : "Client - Admin",
		"active" : 0,
		"company" : "eWheel",
		"active" : 0,
		"street" : "Str",
		"phone" : null,
		"fax" : null,
		"mobile" : null,
		"profile" : "",
		"country" : "BE",
		"city" : "Freudenstadt"
	}
]
;
