import * as React from 'react';
import { Box, Icon, Typography } from '@mui/material';
import Head from 'next/head'
import NavDrawer from '../layout/NavDrawer';


const Customers = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Customers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          '& > :not(style)': {
            m: 2,
          },
        }}
      >

        <Icon>star</Icon>
        <Icon>add_circle</Icon>
      </Box>
    </>
  )
}

Customers.Layout = NavDrawer;

export default Customers;