import Head from 'next/head'
import NavDrawer from '../layout/NavDrawer';


const Documents = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Documents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

Documents.Layout = NavDrawer;

export default Documents;