import Head from "next/head";
import NavDrawer from "../layout/NavDrawer";
import Dashboard from "./admin/dashboard";

const Home = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Dashboard /> */}
    </>
  );
};

Home.Layout = NavDrawer;

export default Home;
