import Head from 'next/head'
import NavDrawer from '../layout/NavDrawer';


const Items = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Items</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

Items.Layout = NavDrawer;

export default Items;