import Head from 'next/head'
import NavDrawer from '../layout/NavDrawer';
import Dashboard from './admin/dashboard'


const Orders = () => {
  return (
    <>
      <Head>
        <title>eWheel2 | Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </>
  )
}

Orders.Layout = NavDrawer;

export default Orders;